project_id = "kuwrhanybqhfnwvshedl"

[functions.api-countries]
verify_jwt = false

[functions.api-cmp-overview]
verify_jwt = false

[functions.api-viewer-sign]
verify_jwt = false

[functions.api-da-revit-job]
verify_jwt = false

[functions.webhooks-aps]
verify_jwt = false

[functions.ingest-monthly]
verify_jwt = false

[functions.post-ingest-refresh]
verify_jwt = false