project_id = "kuwrhanybqhfnwvshedl"

[functions.api-countries]
verify_jwt = false

[functions.api-cmp-overview]
verify_jwt = false

[functions.api-viewer-sign]
verify_jwt = false

[functions.api-da-revit-job]
verify_jwt = false

[functions.api-da-status]
verify_jwt = false

[functions.webhooks-aps]
verify_jwt = false

[functions.auth-aps-start]
verify_jwt = false

[functions.auth-aps-callback]
verify_jwt = false

[functions.auth-aps-status]
verify_jwt = false

[functions.acc-proxy]
verify_jwt = false

[functions.acc-projects-sync]
verify_jwt = false

[functions.ingest-monthly]
verify_jwt = false

[functions.post-ingest-refresh]
verify_jwt = false

[functions.api-cmp-files]
verify_jwt = false

[functions.api-detailed-solution]
verify_jwt = false

[functions.api-hfb]
verify_jwt = false

[functions.aps-hubs]
verify_jwt = false

[functions.auth-aps-debug]
verify_jwt = false