name: Mirror to public

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false   # don't use GITHUB_TOKEN

      - name: Configure git
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Add mirror remote (PAT auth)
        run: |
          git remote add mirror "https://tarekelali:${{ secrets.MIRROR_TOKEN }}@github.com/tarekelali/geo-scope-pilot-mirror.git"
          git remote -v
          git ls-remote --heads mirror || true

      - name: Push all refs (verbose, force)
        env:
          GIT_TRACE: "1"
          GIT_CURL_VERBOSE: "1"
        run: |
          set -euxo pipefail
          git fetch --all
          # push branches and tags; this avoids rare --mirror edge cases
          for b in $(git for-each-ref --format='%(refname:short)' refs/heads/); do
            git push --force mirror "$b:$b"
          done
          git push --force --tags mirror
