name: Mirror to public

on:
  push:
    branches: [ "main" ]
    tags: [ "*" ]
  workflow_dispatch:
    inputs:
      debug:
        description: "Enable verbose git logs"
        required: false
        default: "false"

permissions:
  contents: read

# 👇 edit these two to match your public mirror
env:
  PUBLIC_OWNER: tarekelali
  PUBLIC_REPO: geo-scope-pilot-mirror

concurrency:
  group: mirror-${{ github.ref }}
  cancel-in-progress: false

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
          persist-credentials: false   # don't use GITHUB_TOKEN for pushes

      - name: Optional debug
        if: ${{ github.event.inputs.debug == 'true' }}
        run: |
          echo "GIT_TRACE=1" >> $GITHUB_ENV
          echo "GIT_CURL_VERBOSE=1" >> $GITHUB_ENV

      - name: Configure git
        run: |
          git config --global user.name "mirror-bot"
          git config --global user.email "mirror-bot@users.noreply.github.com"

      - name: Add mirror remote (PAT auth)
        env:
          MIRROR_TOKEN: ${{ secrets.MIRROR_TOKEN }}
          PUBLIC_OWNER: ${{ env.PUBLIC_OWNER }}
          PUBLIC_REPO: ${{ env.PUBLIC_REPO }}
        run: |
          if [ -z "$MIRROR_TOKEN" ]; then
            echo "::error::MIRROR_TOKEN secret is missing"; exit 1; fi
          MIRROR_URL="https://${MIRROR_TOKEN}@github.com/${PUBLIC_OWNER}/${PUBLIC_REPO}.git"
          git remote add mirror "$MIRROR_URL"
          git remote -v

      - name: Push all refs (verbose, force)
        run: |
          git show-ref || true
          # probe first to surface clear permission errors (e.g. workflow scope)
          git push mirror HEAD:_mirror_probe -f
          # mirror everything: branches, tags, notes, etc.
          git push mirror --mirror --prune --force
